### PR TITLE
Remove depedency on glfw so (in theory) should work with SDL and DRM backends

### PR DESCRIPTION
**Pull request by electronstudio**

### CODE REVIEW

**Comment by electronstudio** [comment]
gamepad input has not been tested
there may be more stuff from https://github.com/raylib-extras/rlImGui that could be added

**Comment by electronstudio** [comment]
have not tested with SDL and DRM backends

**Comment by Scr44gr** [comment]
@electronstudio I already tested the gamepad and it works perfectly!

we can enable it with:

```python
imgui.get_io().config_flags |= imgui.ConfigFlags_.nav_enable_gamepad
```

**Comment by Scr44gr** [comment]
also test with SDL and works!

**Pull request merged**
